package org.strigate.ferrot.domain.usecase

import org.strigate.ferrot.domain.usecase.settings.GetAutomaticAppUpdatesEnabledSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetAutomaticDependencyUpdatesEnabledSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetAutomaticDuplicateDownloadDeletionEnabledSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetCookiesEnabledSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetLeftSwipeActionSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetRightSwipeActionSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.GetWifiOnlyDownloadsEnabledSettingAsFlowUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveAutomaticAppUpdatesEnabledSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveAutomaticDependencyUpdatesEnabledSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveAutomaticDuplicateDownloadDeletionEnabledSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveCookiesEnabledSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveLeftSwipeActionSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveRightSwipeActionSettingUseCase
import org.strigate.ferrot.domain.usecase.settings.SaveWifiOnlyDownloadsEnabledSettingUseCase
import javax.inject.Inject

class SettingsUseCase @Inject constructor(
    val saveWifiOnlyDownloadsEnabledSettingUseCase: SaveWifiOnlyDownloadsEnabledSettingUseCase,
    val getWifiOnlyDownloadsEnabledSettingAsFlowUseCase: GetWifiOnlyDownloadsEnabledSettingAsFlowUseCase,
    val saveAutomaticDuplicateDownloadDeletionEnabledSettingUseCase: SaveAutomaticDuplicateDownloadDeletionEnabledSettingUseCase,
    val getAutomaticDuplicateDownloadDeletionEnabledSettingAsFlowUseCase: GetAutomaticDuplicateDownloadDeletionEnabledSettingAsFlowUseCase,
    val saveCookiesEnabledSettingUseCase: SaveCookiesEnabledSettingUseCase,
    val getCookiesEnabledSettingAsFlowUseCase: GetCookiesEnabledSettingAsFlowUseCase,
    val saveLeftSwipeActionSettingUseCase: SaveLeftSwipeActionSettingUseCase,
    val getLeftSwipeActionSettingAsFlowUseCase: GetLeftSwipeActionSettingAsFlowUseCase,
    val saveRightSwipeActionSettingUseCase: SaveRightSwipeActionSettingUseCase,
    val getRightSwipeActionSettingAsFlowUseCase: GetRightSwipeActionSettingAsFlowUseCase,
    val saveAutomaticAppUpdatesEnabledSettingUseCase: SaveAutomaticAppUpdatesEnabledSettingUseCase,
    val getAutomaticAppUpdatesEnabledSettingAsFlowUseCase: GetAutomaticAppUpdatesEnabledSettingAsFlowUseCase,
    val saveAutomaticDependencyUpdatesEnabledSettingUseCase: SaveAutomaticDependencyUpdatesEnabledSettingUseCase,
    val getAutomaticDependencyUpdatesEnabledSettingAsFlowUseCase: GetAutomaticDependencyUpdatesEnabledSettingAsFlowUseCase,
)
